/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Producto;

//Acá importé la librería para los nombres desplazables de los botones
import CLASS.GENERAL_CLASS;

import desplazable.Desface;//ACÁ IMPORTÉ LA LIBRERÍA PARA EL MENÚ DESPLAZABLE DE LA DERECHA

import javax.swing.JTextField;

/**
 *
 * @author Edwin
 */
public class KardesProducto extends javax.swing.JFrame {

    Desface desplace;// ACÁ INSTANCIÉ EL COMPONENTE de la libreria desplazable

    /**
     * Creates new form Startt
     */
    public KardesProducto() {
        initComponents();
       JTextField  Text1[]={
       Codigo,Descripcion,Existecia,Embalaje,TipoMovimientos,Bodega
       };
        Text=Text1;
        String Pop []={"Codigo","Descripcion Producto","Existencia","Embalaje","Tipo Movimiento","Bodegas"};
        general.TextProp(Text1, Pop);
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Menu_Central = new javax.swing.JPanel();
        txt_Estadisticos = new javax.swing.JLabel();
        txt_Ag_Usuario = new javax.swing.JLabel();
        txt_Ventas = new javax.swing.JLabel();
        txt_bodega = new javax.swing.JLabel();
        txt_Producto = new javax.swing.JLabel();
        txt_Informes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BTN_BUSCAR = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        logo_claro = new javax.swing.JLabel();
        logo_oscuro = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        TipoMovimientos = new javax.swing.JTextField();
        Bodega = new javax.swing.JTextField();
        Existecia = new javax.swing.JTextField();
        Embalaje = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BTN_BUSCAR2 = new javax.swing.JButton();
        jDatePicker1 = new org.jdatepicker.JDatePicker();
        jDatePicker2 = new org.jdatepicker.JDatePicker();
        MenuPrincipal = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(10, 15, 42));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_Central.setBackground(new java.awt.Color(16, 34, 43));
        Menu_Central.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Menu_Central.setForeground(new java.awt.Color(255, 255, 255));
        Menu_Central.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Estadisticos.setBackground(new java.awt.Color(34, 40, 44));
        txt_Estadisticos.setForeground(new java.awt.Color(255, 255, 255));
        txt_Estadisticos.setText("ESTADÍSTICOS");
        txt_Estadisticos.setOpaque(true);
        Menu_Central.add(txt_Estadisticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 31, -1, -1));

        txt_Ag_Usuario.setBackground(new java.awt.Color(34, 40, 44));
        txt_Ag_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_Ag_Usuario.setText("+ USUARIO");
        txt_Ag_Usuario.setOpaque(true);
        Menu_Central.add(txt_Ag_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 150, -1, -1));

        txt_Ventas.setBackground(new java.awt.Color(34, 40, 44));
        txt_Ventas.setForeground(new java.awt.Color(255, 255, 255));
        txt_Ventas.setText("VENTAS");
        txt_Ventas.setOpaque(true);
        Menu_Central.add(txt_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 200, -1, -1));

        txt_bodega.setBackground(new java.awt.Color(34, 40, 44));
        txt_bodega.setForeground(new java.awt.Color(255, 255, 255));
        txt_bodega.setText("BODEGA");
        txt_bodega.setOpaque(true);
        Menu_Central.add(txt_bodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 250, -1, -1));

        txt_Producto.setBackground(new java.awt.Color(34, 40, 44));
        txt_Producto.setForeground(new java.awt.Color(255, 255, 255));
        txt_Producto.setText("+ PRODUCTO");
        txt_Producto.setOpaque(true);
        Menu_Central.add(txt_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 300, -1, -1));

        txt_Informes.setBackground(new java.awt.Color(34, 40, 44));
        txt_Informes.setForeground(new java.awt.Color(255, 255, 255));
        txt_Informes.setText("INFORMES");
        txt_Informes.setOpaque(true);
        Menu_Central.add(txt_Informes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 350, -1, -1));

        jScrollPane1.setBorder(null);

        jPanel5.setBackground(new java.awt.Color(10, 15, 42));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("STXinwei", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kardex Producto");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 200, 30));

        BTN_BUSCAR.setBackground(new java.awt.Color(11, 24, 29));
        BTN_BUSCAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_BUSCAR.setText("Consultar");
        BTN_BUSCAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(BTN_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 550, 90, 40));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jetxcel");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 50));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_10px.png"))); // NOI18N
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px.png"))); // NOI18N
        jPanel5.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 30, 30));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_10px_1.png"))); // NOI18N
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 20, 20));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_32px.png"))); // NOI18N
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 90, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_launch_30px_3.png"))); // NOI18N
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 40, 40));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_32px.png"))); // NOI18N
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, -1, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_rocket_40px.png"))); // NOI18N
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 50, 50));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px_2.png"))); // NOI18N
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px_2.png"))); // NOI18N
        jPanel5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 330, 20, 20));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_astronaut_40px_1.png"))); // NOI18N
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 40, 40));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_asteroid_50px_4.png"))); // NOI18N
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, 40));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_shooting_stars_50px_1.png"))); // NOI18N
        jPanel5.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 60, 60));

        logo_claro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_rocket_take_off_50px.png"))); // NOI18N
        jPanel5.add(logo_claro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        logo_oscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_rocket_take_off_50px_1.png"))); // NOI18N
        jPanel5.add(logo_oscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        Codigo.setBackground(new java.awt.Color(16, 34, 43));
        Codigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Codigo.setForeground(new java.awt.Color(255, 255, 255));
        Codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodigoMouseClicked(evt);
            }
        });
        jPanel5.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        Descripcion.setBackground(new java.awt.Color(16, 34, 43));
        Descripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Descripcion.setForeground(new java.awt.Color(255, 255, 255));
        Descripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescripcionMouseClicked(evt);
            }
        });
        jPanel5.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 250, 30));

        TipoMovimientos.setBackground(new java.awt.Color(16, 34, 43));
        TipoMovimientos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TipoMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        TipoMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TipoMovimientosMouseClicked(evt);
            }
        });
        jPanel5.add(TipoMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 260, 30));

        Bodega.setBackground(new java.awt.Color(16, 34, 43));
        Bodega.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Bodega.setForeground(new java.awt.Color(255, 255, 255));
        Bodega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BodegaMouseClicked(evt);
            }
        });
        jPanel5.add(Bodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 130, 30));

        Existecia.setBackground(new java.awt.Color(16, 34, 43));
        Existecia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Existecia.setForeground(new java.awt.Color(255, 255, 255));
        Existecia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExisteciaMouseClicked(evt);
            }
        });
        jPanel5.add(Existecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 70, 30));

        Embalaje.setBackground(new java.awt.Color(16, 34, 43));
        Embalaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Embalaje.setForeground(new java.awt.Color(255, 255, 255));
        Embalaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmbalajeMouseClicked(evt);
            }
        });
        jPanel5.add(Embalaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 70, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setInheritsPopupMenu(true);
        jTable1.setOpaque(false);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable1);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1220, 420));

        BTN_BUSCAR2.setBackground(new java.awt.Color(11, 24, 29));
        BTN_BUSCAR2.setForeground(new java.awt.Color(255, 255, 255));
        BTN_BUSCAR2.setText("Exportar Informe");
        BTN_BUSCAR2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(BTN_BUSCAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 550, 120, 40));

        jDatePicker1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, 120, -1));

        jDatePicker2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDatePicker2.setOpaque(true);
        jPanel5.add(jDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 120, 30));

        jScrollPane1.setViewportView(jPanel5);

        Menu_Central.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1250, 630));

        MenuPrincipal.setBackground(new java.awt.Color(10, 15, 42));
        MenuPrincipal.setVisible(false);
        Menu_Central.add(MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 940));

        jPanel2.add(Menu_Central, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1270, 650));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1269, 662));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoMouseClicked

    private void DescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMouseClicked

    private void TipoMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TipoMovimientosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoMovimientosMouseClicked

    private void BodegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BodegaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BodegaMouseClicked

    private void ExisteciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExisteciaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ExisteciaMouseClicked

    private void EmbalajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmbalajeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EmbalajeMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KardesProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KardesProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KardesProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KardesProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KardesProducto().setVisible(true);
            }
        });
    }
    public GENERAL_CLASS general = new GENERAL_CLASS();
    public JTextField Text[];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BUSCAR;
    private javax.swing.JButton BTN_BUSCAR2;
    private javax.swing.JTextField Bodega;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JTextField Embalaje;
    private javax.swing.JTextField Existecia;
    private java.awt.Panel MenuPrincipal;
    private javax.swing.JPanel Menu_Central;
    private javax.swing.JTextField TipoMovimientos;
    private org.jdatepicker.JDatePicker jDatePicker1;
    private org.jdatepicker.JDatePicker jDatePicker2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logo_claro;
    private javax.swing.JLabel logo_oscuro;
    private javax.swing.JLabel txt_Ag_Usuario;
    private javax.swing.JLabel txt_Estadisticos;
    private javax.swing.JLabel txt_Informes;
    private javax.swing.JLabel txt_Producto;
    private javax.swing.JLabel txt_Ventas;
    private javax.swing.JLabel txt_bodega;
    // End of variables declaration//GEN-END:variables
}
