/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOME;

import CLASS.CONEXION_MySQL;
import CLASS.GENERAL_CLASS;
import CLASS.MySQL_Query;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import javax.swing.JTextField;

/**
 *
 * @author JAVIER
 */
public final class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Bodegas
     * @param Queryes
     * @param ini
     */
    public Configuracion(MySQL_Query Queryes, boolean ini)  {
        initComponents();
         Querys=  Queryes;
         ini= inic;
         activa(ini);
         Conn= new CONEXION_MySQL();
         Queryes.SetLabel(NameUser,ContraUser,HotsName,NameBD);
         try{
         IniciarData();
         }catch(SQLException ex){
             System.out.println(ex.getMessage());
         }
         
    }
    public void activa(Boolean x){
        NombreEmpresa.setEnabled(x);
        Nit.setEnabled(x);
        IntidacorCo.setEnabled(x);
        NombreReprecentante.setEnabled(x);
        Telefono.setEnabled(x);
        Direccion.setEnabled(x);
        Email.setEnabled(x);
        Regimen.setEnabled(x);
        jButton3.setEnabled(x);
        jButton7.setEnabled(x);
        jButton8.setEnabled(!x);
    }
    private Configuracion() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NombreEmpresa = new javax.swing.JTextField();
        Nit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        NombreReprecentante = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Direccion = new javax.swing.JTextField();
        IntidacorCo = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        OffLine = new javax.swing.JRadioButton();
        OnLine = new javax.swing.JRadioButton();
        Auto = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Regimen = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NameBD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        HotsName = new javax.swing.JTextField();
        NameUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        ContraUser = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CREAR BODEGAS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(65, 65, 65));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 57, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(65, 65, 65));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.ButtonGroup grupo = new javax.swing.ButtonGroup();
        grupo.add(OnLine);
        grupo.add(OffLine);
        grupo.add(Auto);
        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setForeground(new java.awt.Color(0, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Foto2.png"))); // NOI18N
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 100));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 170, 120));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nombre empresa");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        NombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEmpresaActionPerformed(evt);
            }
        });
        jPanel7.add(NombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 30));

        Nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NitActionPerformed(evt);
            }
        });
        jPanel7.add(Nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 150, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NIT/CC");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        NombreReprecentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreReprecentanteActionPerformed(evt);
            }
        });
        jPanel7.add(NombreReprecentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre Reprecentante Legal");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Telefono");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        jPanel7.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 190, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Direccion");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        jPanel7.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 30));

        IntidacorCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntidacorCoActionPerformed(evt);
            }
        });
        jPanel7.add(IntidacorCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 30, 30));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Agregar.png"))); // NOI18N
        jButton6.setText("AGREGAR");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 170, 50));

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Actualizar.png"))); // NOI18N
        jButton7.setText("ACTUALIZAR");
        jButton7.setHideActionText(true);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 170, 50));

        OffLine.setBackground(new java.awt.Color(204, 255, 255));
        OffLine.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        OffLine.setForeground(new java.awt.Color(255, 255, 255));
        OffLine.setText("OffLine");
        jPanel7.add(OffLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        OnLine.setBackground(new java.awt.Color(204, 255, 255));
        OnLine.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        OnLine.setForeground(new java.awt.Color(255, 255, 255));
        OnLine.setText("OnLine");
        jPanel7.add(OnLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        Auto.setBackground(new java.awt.Color(204, 255, 255));
        Auto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Auto.setForeground(new java.awt.Color(255, 255, 255));
        Auto.setText("Automatico");
        jPanel7.add(Auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Examinar (2).png"))); // NOI18N
        jButton3.setText("EXAMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 170, 60));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Email");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel7.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 190, 30));

        Regimen.setBackground(new java.awt.Color(204, 204, 204));
        Regimen.setEditable(true);
        Regimen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Regimen.setForeground(new java.awt.Color(255, 255, 255));
        Regimen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIMPLIFICADO", "COMUN" }));
        org.jdesktop.swingx.autocomplete.AutoCompleteDecorator.decorate(Regimen);
        Regimen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegimenActionPerformed(evt);
            }
        });
        Regimen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RegimenKeyReleased(evt);
            }
        });
        jPanel7.add(Regimen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 140, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Regimen");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 70, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Modificar.png"))); // NOI18N
        jButton8.setText("MODIFICAR");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 50));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 370));

        jTabbedPane1.addTab("CONFIGURACION BASICA", jPanel5);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Wifi1.png"))); // NOI18N
        jButton4.setText("TEST DE CONEXION");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de Base de Datos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        NameBD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(NameBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Base_Datos.png"))); // NOI18N
        jLabel5.setText(" ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 130, 140));

        HotsName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(HotsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 180, 30));

        NameUser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(NameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario Login");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña de Login");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Disquet 1.png"))); // NOI18N
        jButton5.setText("GUARDAR");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 160, 60));

        ContraUser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(ContraUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 180, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("será errónea y no se podrán cargar los datos.....");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre Host / IP");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("Precaución !");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 0));
        jLabel21.setText("A la hora de realizar la conexión tener en cuenta, ingresar");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 0));
        jLabel22.setText("cada una de las letras que correspondan correctamente");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setText("al usuario y contraseña designados, sino la conexión será");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jTabbedPane1.addTab("CONFIGURACION BD", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.addTab("RESOLUCION VENTAS", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.addTab("RESOLUCION COMPRA", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 650, 400));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" ");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PARAMETROS BASICOS");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//Conn.EscribirXML(NameUser.getText(), ContraUser.getText(), NameBD.getText(), HotsName.getText());       // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Conn.Conexion();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void NombreReprecentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreReprecentanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreReprecentanteActionPerformed

    private void IntidacorCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntidacorCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntidacorCoActionPerformed

    private void NombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEmpresaActionPerformed

    private void NitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NitActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void RegimenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegimenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegimenActionPerformed

    private void RegimenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegimenKeyReleased
        //Keys(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_RegimenKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        //imagen =general.AgregarImagenBit(general.Exan(jPanel1)).toString();
           imagen= general.AgregarImagenBit(general.Exan(jPanel1));
        }catch(Exception ex){
          
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    activa(false);               // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
    public void IniciarData() throws SQLException{
          ResultSet resultado = Querys.InicioEmpresa();
        JTextField Text[] = {NombreEmpresa,Nit,
                            IntidacorCo,
                            NombreReprecentante,
                           Telefono,Email, Direccion};
         general.TextLlenarSQL(resultado, Text);
                 try{
                     ResultSet Logos = Querys.InicioEmpresa();
                    while(Logos.next()){
                        if(Logos.getString(9) != null){
                            jButton6.setEnabled(false);
                        }else{
                        jButton6.setEnabled(true);
                        }
                        if (Logos.getBytes(8) != null) {
                    byte[] bi = Logos.getBytes(8);
                    Regimen.setSelectedItem(Logos.getString(9));
                    general.InsertarImagenLabel(bi, jLabel1);
                        }else{
                         jLabel1.setText("No imagen");

                        }
                 
                   
                    }
                }catch( SQLException ex){
                    jLabel1.setText("No imagen");
                }
        
      
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            String Nombre = NombreEmpresa.getText();
            String NIT= Nit.getText();
            String Representate =NombreReprecentante.getText();
            String Indicador = IntidacorCo.getText();
            String Telefonos =Telefono.getText();
            String Direcciones= Direccion.getText();
            String Emails= Email.getText();
            String RegimeTipo = Regimen.getSelectedItem().toString();
            
            Querys.InsetEmpresa(Nombre, NIT, Indicador, RegimeTipo,
                    Representate, Telefonos, Emails, Direcciones, imagen);
            IniciarData();
        } catch (SQLException ex) {
            Logger.getLogger(Configuracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
activa(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Configuracion().setVisible(true);
        });
    }
    private boolean inic;
    private byte[] imagen =null;
    private MySQL_Query Querys;
    public GENERAL_CLASS general = new GENERAL_CLASS();
    private CONEXION_MySQL Conn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Auto;
    private javax.swing.JPasswordField ContraUser;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField HotsName;
    private javax.swing.JTextField IntidacorCo;
    private javax.swing.JTextField NameBD;
    private javax.swing.JTextField NameUser;
    private javax.swing.JTextField Nit;
    private javax.swing.JTextField NombreEmpresa;
    private javax.swing.JTextField NombreReprecentante;
    private javax.swing.JRadioButton OffLine;
    private javax.swing.JRadioButton OnLine;
    private javax.swing.JComboBox<String> Regimen;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
