/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOME;

import ALMACEN.ActualizarPrecios;
import ALMACEN.AjusteInventario;
import ALMACEN.CREARITEM.CrearBodegas;
import ALMACEN.CREARITEM.CrearInventario;
import ALMACEN.CREARITEM.CrearProducto;
import ALMACEN.CREARITEM.FAMILIA1;
import ALMACEN.CREARITEM.FAMILIA2;
import ALMACEN.CREARITEM.FAMILIA3;
import ALMACEN.CREARITEM.IMPUESTO;
import ALMACEN.CREARITEM.UNDMEDIDA;
import ALMACEN.EntradaMercancia;
import ALMACEN.InventarioGeneral;
import ALMACEN.OrdenesPedido;
import ALMACEN.Usuario;

import CLASS.GENERAL_CLASS;
import CLASS.MySQL_Query;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Edwin
 */
public class Login extends javax.swing.JFrame {

    /**
     * 
     * Creates new form Login
     */
    public Login() throws InterruptedException {
        initComponents();
           
    }

    public static void CargarVentanas(FAMILIA1 WinFm_1,FAMILIA2 WinFm_2,FAMILIA3 WinFm_3,UNDMEDIDA WindFnidad_,CrearBodegas WinCrearBG_,Usuario WinUser_,Configuracion WinConf_){
    
    
            WinFm1 =WinFm_1;
            JOptionPane.showMessageDialog(null,WinFm1.toString());
            WinFm2= WinFm_2 ;
             JOptionPane.showMessageDialog(null,WinFm2.toString());
            WinFm3  =WinFm_3;
            JOptionPane.showMessageDialog(null,WinFm3.toString());
            WindFnidad =WindFnidad_ ;
            JOptionPane.showMessageDialog(null,WindFnidad.toString());
            WinCrearBG  =WinCrearBG_;
            JOptionPane.showMessageDialog(null,WinCrearBG.toString());
            WinUser =WinUser_;
            JOptionPane.showMessageDialog(null,WinUser.toString());
            WinConf=WinConf_;
            JOptionPane.showMessageDialog(null,WinConf.toString());
           // st= new Start(WinFm_1,WinFm_2,WinFm_3,WindFnidad_,WinCrearBG_,WinUser_,WinConf_);
           //JOptionPane.showMessageDialog(null,st.toString());
            
    }
    /*   private Login() {
    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dtas = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        loadingnum = new javax.swing.JLabel();
        Texto_Contraseña = new javax.swing.JLabel();
        Titulo_InicioSesion = new javax.swing.JLabel();
        Texto_Usuario = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        Ingresar = new javax.swing.JLabel();
        No_Mostrar = new javax.swing.JLabel();
        Mostrar = new javax.swing.JLabel();
        Ojo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Copyrigth1 = new javax.swing.JLabel();
        Copyrigth = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fondo_Pantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dtas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dtas.setForeground(new java.awt.Color(255, 255, 255));
        Dtas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dtas.setText("99 %");
        getContentPane().add(Dtas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        loadingbar.setBackground(new java.awt.Color(0, 204, 204));
        loadingbar.setForeground(new java.awt.Color(0, 204, 204));
        loadingbar.setBorderPainted(false);
        loadingbar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                loadingbarStateChanged(evt);
            }
        });
        loadingbar.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                loadingbarVetoableChange(evt);
            }
        });
        getContentPane().add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 490, 10));

        loadingnum.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        loadingnum.setForeground(new java.awt.Color(255, 255, 255));
        loadingnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadingnum.setText("99  %");
        getContentPane().add(loadingnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, -1, 20));

        Texto_Contraseña.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        Texto_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Contraseña.setText("Pass");
        getContentPane().add(Texto_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        Titulo_InicioSesion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Titulo_InicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_InicioSesion.setText("INICIO DE SESIÓN");
        getContentPane().add(Titulo_InicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        Texto_Usuario.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        Texto_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Usuario.setText("User");
        getContentPane().add(Texto_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        jTextField1.setBackground(new java.awt.Color(35, 49, 62));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 230, 25));

        jPasswordField1.setBackground(new java.awt.Color(35, 49, 62));
        jPasswordField1.setFont(jPasswordField1.getFont().deriveFont(jPasswordField1.getFont().getSize()+3f));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPasswordField1.setOpaque(false);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 210, 22));

        Ingresar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        Ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ingresar.setText("Iniciar");
        Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarMouseClicked(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 82, 25));

        No_Mostrar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        No_Mostrar.setForeground(new java.awt.Color(204, 204, 204));
        No_Mostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        No_Mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        No_Mostrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        No_Mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                No_MostrarMouseClicked(evt);
            }
        });
        getContentPane().add(No_Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 412, 30, 20));

        Mostrar.setForeground(new java.awt.Color(255, 255, 255));
        Mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Chulito_Cerrado.png"))); // NOI18N
        Mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarMouseClicked(evt);
            }
        });
        getContentPane().add(Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 412, 20, 20));

        Ojo.setBackground(new java.awt.Color(102, 102, 102));
        Ojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Chulito_Abierto.png"))); // NOI18N
        Ojo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Ojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 412, -1, 20));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iniciar_Sesion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        Copyrigth1.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        Copyrigth1.setForeground(new java.awt.Color(255, 255, 255));
        Copyrigth1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Espacio_texto.png"))); // NOI18N
        getContentPane().add(Copyrigth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        Copyrigth.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        Copyrigth.setForeground(new java.awt.Color(255, 255, 255));
        Copyrigth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Espacio_texto.png"))); // NOI18N
        getContentPane().add(Copyrigth, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("+");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 272, 20, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 14, -1, 15));

        Fondo_Pantalla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Fondo_Pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Liggin.png"))); // NOI18N
        getContentPane().add(Fondo_Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        setSize(new java.awt.Dimension(843, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);// Acá es para cerrar la pestaña de Login y saalir del programa
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void MostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarMouseClicked
        No_Mostrar.setVisible(true);// Acá es al dar clic para mostrar contraseña
        No_Mostrar.setEnabled(true);
        jPasswordField1.setEchoChar((char)0);
        
        Mostrar.setVisible(false);
        Mostrar.setEnabled(false);
    }//GEN-LAST:event_MostrarMouseClicked

    private void No_MostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_No_MostrarMouseClicked
        
        Mostrar.setVisible(true);// Acá es para desactivar el mostrar contraseña o  desactivar ver contraseña
        Mostrar.setEnabled(true);
        jPasswordField1.setEchoChar((char)8226);
        No_Mostrar.setVisible(false);
        No_Mostrar.setEnabled(false);
       
    }//GEN-LAST:event_No_MostrarMouseClicked

    private void IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseClicked
        
        st.setVisible(true);
        this.setVisible(false);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setExtendedState(ICONIFIED);//Minimizar Pantalla Login
    }//GEN-LAST:event_jLabel2MouseClicked

    private void loadingbarVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_loadingbarVetoableChange
              // TODO add your handling code here:
    }//GEN-LAST:event_loadingbarVetoableChange

    private void loadingbarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_loadingbarStateChanged
      // TODO add your handling code here:
    }//GEN-LAST:event_loadingbarStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        new Login().setVisible(true); 
        
        Ingresar.setEnabled(false);
        try {
            
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(20);
                 if(i==1){
                    Querys = new MySQL_Query(Dtas);
                }
                if (i==5) {
                  WindFnidad  = new UNDMEDIDA(Querys,true);
                }
                if (i==10) {
                    WinCrearBG =new CrearBodegas(Querys,false);
                }
                if (i==15) {
                    WinFm3 =  new FAMILIA3 (Querys,true);
                }if (i==20) {
                    WinFm2 = new FAMILIA2(Querys,true);
                }if (i==25){
                    WinFm1= new FAMILIA1(Querys,true);
                }if (i == 30) {
                    WinConf= new  Configuracion(Querys,false);
                }if (i==40) {
                    WinUser= new Usuario(Querys,false );
                }if (i==50) {
                    WinImpuesto = new IMPUESTO (Querys,true);
                }
                if (i==60) {
                    win = new CrearProducto(Querys, false, WinCrearBG, WinImpuesto, WinFm1, WinFm2, WinFm3, WindFnidad);
                }
                if(i==70){
                st= new Startt(WinFm1, WinFm2, WinFm3, WindFnidad, WinCrearBG, WinUser, WinConf,win);
                }
                 
                loadingnum.setText(Integer.toString(i)+"%");// Acà se incrementan los nùmeros de porcentaje de cargando, hay un error, los nùmeros no para de cargar
                loadingbar.setValue(i); //Con esta parte se llena la barra de cargando
                if(i==100){
                   try{
                     //  CargarVentanas(WinFm1, WinFm2, WinFm3, WindFnidad, WinCrearBG, WinUser, WinConf);
                       Ingresar.setEnabled(true);
                       loadingbar.setBackground(Color.GREEN);
                         //Acà oculta la pantalla de Intro o Splash nombrada "Screen"

                   }catch(Exception ex){
                   JOptionPane.showMessageDialog(null,"Error aqui " + ex.getMessage());
                   }
            
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error "+ e.getMessage() );
        }
    }
        public static MySQL_Query Querys ;
        public static FAMILIA1 WinFm1;
        public static FAMILIA2 WinFm2  ;
        public static FAMILIA3 WinFm3  ;
        public static UNDMEDIDA WindFnidad ;
        public static CrearBodegas WinCrearBG  ;
        public  static Usuario WinUser ;
        public static Configuracion WinConf;
        public static   CrearProducto win;
    // Declaracion de Variables
    //Parametros Basicos
 
    //Bodega
   public  static OrdenesPedido WinOP = new OrdenesPedido();
   public static EntradaMercancia WinEntraBD = new EntradaMercancia();
   public static AjusteInventario WinAjInventario= new AjusteInventario();
   public static CrearInventario WinCrearInventario = new CrearInventario();
   public static InventarioGeneral WinInvG = new InventarioGeneral();
   public static ActualizarPrecios WinActulizar = new ActualizarPrecios();
  // public MotorUpdateJava win1= new MotorUpdateJava();
    //PRODUCTO
   public static IMPUESTO WinImpuesto ;
   public static   GENERAL_CLASS Clases = new GENERAL_CLASS();
   
  
   static Startt st;

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Copyrigth;
    private javax.swing.JLabel Copyrigth1;
    public static javax.swing.JLabel Dtas;
    private javax.swing.JLabel Fondo_Pantalla;
    public static javax.swing.JLabel Ingresar;
    private javax.swing.JLabel Mostrar;
    private javax.swing.JLabel No_Mostrar;
    private javax.swing.JLabel Ojo;
    private javax.swing.JLabel Texto_Contraseña;
    private javax.swing.JLabel Texto_Usuario;
    private javax.swing.JLabel Titulo_InicioSesion;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JProgressBar loadingbar;
    public static javax.swing.JLabel loadingnum;
    // End of variables declaration//GEN-END:variables
}
