/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOME;

import Producto.*;
import HOME.*;
import ALMACEN.CrearBodegas;
import Producto.CrearProducto;
import Producto.FAMILIA1;
import Producto.FAMILIA2;
import Producto.FAMILIA3;
import Producto.UNDMEDIDA;
import USUARIO.Usuario;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
import AppPackage.AnimationClass;//Acá importé la librería para los nombres desplazables de los botones
import CLASS.GENERAL_CLASS;
import HOME.*;
import java.awt.Dimension;
import desplazable.Desface;//ACÁ IMPORTÉ LA LIBRERÍA PARA EL MENÚ DESPLAZABLE DE LA DERECHA
import javax.swing.JPanel;

/**
 *
 * @author Edwin
 */
public class Plantilla extends javax.swing.JFrame {

    Desface desplace;// ACÁ INSTANCIÉ EL COMPONENTE de la libreria desplazable

    /**
     * Creates new form Startt
     */
    public Plantilla() {
        initComponents();



       
     
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Menu_Central = new javax.swing.JPanel();
        txt_Estadisticos = new javax.swing.JLabel();
        txt_Ag_Usuario = new javax.swing.JLabel();
        txt_Ventas = new javax.swing.JLabel();
        txt_bodega = new javax.swing.JLabel();
        txt_Producto = new javax.swing.JLabel();
        txt_Informes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BTN_BUSCAR = new javax.swing.JButton();
        BOX_BUSCAR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        logo_claro = new javax.swing.JLabel();
        logo_oscuro = new javax.swing.JLabel();
        BOX_BUSCAR1 = new javax.swing.JTextField();
        BOX_BUSCAR2 = new javax.swing.JTextField();
        BOX_BUSCAR3 = new javax.swing.JTextField();
        BOX_BUSCAR4 = new javax.swing.JTextField();
        MenuPrincipal = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(10, 15, 42));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_Central.setBackground(new java.awt.Color(16, 34, 43));
        Menu_Central.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Menu_Central.setForeground(new java.awt.Color(255, 255, 255));
        Menu_Central.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Estadisticos.setBackground(new java.awt.Color(34, 40, 44));
        txt_Estadisticos.setForeground(new java.awt.Color(255, 255, 255));
        txt_Estadisticos.setText("ESTADÍSTICOS");
        txt_Estadisticos.setOpaque(true);
        Menu_Central.add(txt_Estadisticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 31, -1, -1));

        txt_Ag_Usuario.setBackground(new java.awt.Color(34, 40, 44));
        txt_Ag_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_Ag_Usuario.setText("+ USUARIO");
        txt_Ag_Usuario.setOpaque(true);
        Menu_Central.add(txt_Ag_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 150, -1, -1));

        txt_Ventas.setBackground(new java.awt.Color(34, 40, 44));
        txt_Ventas.setForeground(new java.awt.Color(255, 255, 255));
        txt_Ventas.setText("VENTAS");
        txt_Ventas.setOpaque(true);
        Menu_Central.add(txt_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 200, -1, -1));

        txt_bodega.setBackground(new java.awt.Color(34, 40, 44));
        txt_bodega.setForeground(new java.awt.Color(255, 255, 255));
        txt_bodega.setText("BODEGA");
        txt_bodega.setOpaque(true);
        Menu_Central.add(txt_bodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 250, -1, -1));

        txt_Producto.setBackground(new java.awt.Color(34, 40, 44));
        txt_Producto.setForeground(new java.awt.Color(255, 255, 255));
        txt_Producto.setText("+ PRODUCTO");
        txt_Producto.setOpaque(true);
        Menu_Central.add(txt_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 300, -1, -1));

        txt_Informes.setBackground(new java.awt.Color(34, 40, 44));
        txt_Informes.setForeground(new java.awt.Color(255, 255, 255));
        txt_Informes.setText("INFORMES");
        txt_Informes.setOpaque(true);
        Menu_Central.add(txt_Informes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 350, -1, -1));

        jScrollPane1.setBorder(null);

        jPanel5.setBackground(new java.awt.Color(10, 15, 42));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("STXinwei", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kardex Producto");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 200, 30));

        BTN_BUSCAR.setBackground(new java.awt.Color(11, 24, 29));
        BTN_BUSCAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_BUSCAR.setText("BUSCAR");
        BTN_BUSCAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(BTN_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 90, 40));

        BOX_BUSCAR.setBackground(new java.awt.Color(16, 34, 43));
        BOX_BUSCAR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BOX_BUSCAR.setForeground(new java.awt.Color(255, 255, 255));
        BOX_BUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOX_BUSCARMouseClicked(evt);
            }
        });
        jPanel5.add(BOX_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 510, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jetxcel");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 50));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_10px.png"))); // NOI18N
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px.png"))); // NOI18N
        jPanel5.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 30, 30));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_10px_1.png"))); // NOI18N
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 20, 20));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_32px.png"))); // NOI18N
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_launch_30px_3.png"))); // NOI18N
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 160, 40, 40));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_32px.png"))); // NOI18N
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, -1, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_rocket_40px.png"))); // NOI18N
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 50, 50));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px_2.png"))); // NOI18N
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px_2.png"))); // NOI18N
        jPanel5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 30, 30));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_astronaut_40px_1.png"))); // NOI18N
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, 50));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_asteroid_50px_4.png"))); // NOI18N
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 60, 50));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_shooting_stars_50px_1.png"))); // NOI18N
        jPanel5.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 60));

        logo_claro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_rocket_take_off_50px.png"))); // NOI18N
        jPanel5.add(logo_claro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        logo_oscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_rocket_take_off_50px_1.png"))); // NOI18N
        jPanel5.add(logo_oscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        BOX_BUSCAR1.setBackground(new java.awt.Color(16, 34, 43));
        BOX_BUSCAR1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BOX_BUSCAR1.setForeground(new java.awt.Color(255, 255, 255));
        BOX_BUSCAR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOX_BUSCAR1MouseClicked(evt);
            }
        });
        jPanel5.add(BOX_BUSCAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        BOX_BUSCAR2.setBackground(new java.awt.Color(16, 34, 43));
        BOX_BUSCAR2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BOX_BUSCAR2.setForeground(new java.awt.Color(255, 255, 255));
        BOX_BUSCAR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOX_BUSCAR2MouseClicked(evt);
            }
        });
        jPanel5.add(BOX_BUSCAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 600, 30));

        BOX_BUSCAR3.setBackground(new java.awt.Color(16, 34, 43));
        BOX_BUSCAR3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BOX_BUSCAR3.setForeground(new java.awt.Color(255, 255, 255));
        BOX_BUSCAR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOX_BUSCAR3MouseClicked(evt);
            }
        });
        jPanel5.add(BOX_BUSCAR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 130, 30));

        BOX_BUSCAR4.setBackground(new java.awt.Color(16, 34, 43));
        BOX_BUSCAR4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BOX_BUSCAR4.setForeground(new java.awt.Color(255, 255, 255));
        BOX_BUSCAR4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOX_BUSCAR4MouseClicked(evt);
            }
        });
        jPanel5.add(BOX_BUSCAR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 130, 30));

        jScrollPane1.setViewportView(jPanel5);

        Menu_Central.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1220, 610));

        MenuPrincipal.setBackground(new java.awt.Color(10, 15, 42));
        MenuPrincipal.setVisible(false);
        Menu_Central.add(MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 940));

        jPanel2.add(Menu_Central, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 0, 1240, 630));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1269, 662));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BOX_BUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOX_BUSCARMouseClicked
     
    }//GEN-LAST:event_BOX_BUSCARMouseClicked

    private void BOX_BUSCAR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOX_BUSCAR1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_BUSCAR1MouseClicked

    private void BOX_BUSCAR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOX_BUSCAR2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_BUSCAR2MouseClicked

    private void BOX_BUSCAR3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOX_BUSCAR3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_BUSCAR3MouseClicked

    private void BOX_BUSCAR4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOX_BUSCAR4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_BUSCAR4MouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plantilla().setVisible(true);
            }
        });
    }
    public GENERAL_CLASS general = new GENERAL_CLASS();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BOX_BUSCAR;
    private javax.swing.JTextField BOX_BUSCAR1;
    private javax.swing.JTextField BOX_BUSCAR2;
    private javax.swing.JTextField BOX_BUSCAR3;
    private javax.swing.JTextField BOX_BUSCAR4;
    private javax.swing.JButton BTN_BUSCAR;
    private java.awt.Panel MenuPrincipal;
    private javax.swing.JPanel Menu_Central;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_claro;
    private javax.swing.JLabel logo_oscuro;
    private javax.swing.JLabel txt_Ag_Usuario;
    private javax.swing.JLabel txt_Estadisticos;
    private javax.swing.JLabel txt_Informes;
    private javax.swing.JLabel txt_Producto;
    private javax.swing.JLabel txt_Ventas;
    private javax.swing.JLabel txt_bodega;
    // End of variables declaration//GEN-END:variables
}
