/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOME;

/**
 *
 * @author edwin
 */
public class PRODUCTOS_INTERNAL_FORM11 extends javax.swing.JInternalFrame {

    /**
     * Creates new form CLIENTES_INTERNAL_FORM
     */
    public PRODUCTOS_INTERNAL_FORM11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        ESTRELLA_27 = new javax.swing.JLabel();
        HOJA_21 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        ESTRELLA_28 = new javax.swing.JLabel();
        estrella_13 = new javax.swing.JLabel();
        HOJA_28 = new javax.swing.JLabel();
        HOJA_29 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        ESTRELLA_29 = new javax.swing.JLabel();
        HOJA_30 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        ESTRELLA_30 = new javax.swing.JLabel();
        HOJA_31 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jButton28 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        estrella_14 = new javax.swing.JLabel();
        HOJA_32 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jButton29 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jButton30 = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        ESTRELLA_31 = new javax.swing.JLabel();
        HOJA_33 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jButton32 = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        ESTRELLA_33 = new javax.swing.JLabel();
        HOJA_35 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jButton31 = new javax.swing.JButton();
        jLabel67 = new javax.swing.JLabel();
        ESTRELLA_32 = new javax.swing.JLabel();
        HOJA_34 = new javax.swing.JLabel();

        setForeground(java.awt.Color.darkGray);
        setTitle("PRODUCTOS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(6, 10, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBackground(new java.awt.Color(6, 10, 28));
        jPanel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel27.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("CREAR PRODUCTOS");
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel58MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel58MouseExited(evt);
            }
        });
        jPanel27.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        ESTRELLA_27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_rocket_40px.png"))); // NOI18N
        jPanel27.add(ESTRELLA_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 50, 50));

        HOJA_21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_leaf_40px.png"))); // NOI18N
        jPanel27.add(HOJA_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 60, 60));

        jPanel1.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 80));

        jPanel16.setBackground(new java.awt.Color(6, 10, 28));
        jPanel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("DEPARTAMENTO");
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel40MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel40MouseExited(evt);
            }
        });
        jPanel16.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 530, 80));

        jPanel28.setBackground(new java.awt.Color(6, 10, 28));
        jPanel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel28.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("SECCIÓN");
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel59MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel59MouseExited(evt);
            }
        });
        jPanel28.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        ESTRELLA_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_astronaut_40px_1.png"))); // NOI18N
        jPanel28.add(ESTRELLA_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 50, 50));

        estrella_13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_comet_15px.png"))); // NOI18N
        jPanel28.add(estrella_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 20, 30));

        HOJA_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_maple_leaf_40px_1.png"))); // NOI18N
        jPanel28.add(HOJA_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 50, 50));

        HOJA_29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ALMACENV1/src/IMAGENES/icons8_slug_eating_20px.png"))); // NOI18N
        jPanel28.add(HOJA_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 30, -1));

        jPanel1.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 530, 80));

        jPanel29.setBackground(new java.awt.Color(6, 10, 28));
        jPanel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel29.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("FAMILIAS");
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel60MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel60MouseExited(evt);
            }
        });
        jPanel29.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        jPanel1.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 530, 80));

        jPanel30.setBackground(new java.awt.Color(6, 10, 28));
        jPanel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel30.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("SUBFAMILIA");
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel61MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel61MouseExited(evt);
            }
        });
        jPanel30.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        ESTRELLA_29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_astronaut_40px.png"))); // NOI18N
        jPanel30.add(ESTRELLA_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 50, -1));

        HOJA_30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ALMACENV1/src/IMAGENES/icons8_nature_50px.png"))); // NOI18N
        jPanel30.add(HOJA_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 43, -1, -1));

        jPanel1.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 530, 80));

        jPanel31.setBackground(new java.awt.Color(6, 10, 28));
        jPanel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel31.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("CLASIFICACIÓN");
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel62MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel62MouseExited(evt);
            }
        });
        jPanel31.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        jPanel1.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 530, 80));

        jPanel32.setBackground(new java.awt.Color(6, 10, 28));
        jPanel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel32.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("IVA");
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel63MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel63MouseExited(evt);
            }
        });
        jPanel32.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        ESTRELLA_30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px_2.png"))); // NOI18N
        jPanel32.add(ESTRELLA_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 30, 30));

        HOJA_31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ALMACENV1/src/IMAGENES/icons8_wood_32px.png"))); // NOI18N
        jPanel32.add(HOJA_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jPanel1.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 530, 80));

        jPanel33.setBackground(new java.awt.Color(6, 10, 28));
        jPanel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel33.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("CANALES DE PRECIOS");
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel64MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel64MouseExited(evt);
            }
        });
        jPanel33.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        estrella_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_comet_15px.png"))); // NOI18N
        jPanel33.add(estrella_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 20, 30));

        HOJA_32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_koala_32px.png"))); // NOI18N
        jPanel33.add(HOJA_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel1.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 530, 80));

        jPanel34.setBackground(new java.awt.Color(6, 10, 28));
        jPanel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel34.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("LISTA DE PRECIOS");
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel65MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel65MouseExited(evt);
            }
        });
        jPanel34.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        jPanel1.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 530, 80));

        jPanel35.setBackground(new java.awt.Color(6, 10, 28));
        jPanel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel35.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("CREAR EVENTOS");
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel66MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel66MouseExited(evt);
            }
        });
        jPanel35.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        ESTRELLA_31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_saturn_planet_50px.png"))); // NOI18N
        jPanel35.add(ESTRELLA_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        HOJA_33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ALMACENV1/src/IMAGENES/icons8_bug_50px.png"))); // NOI18N
        jPanel35.add(HOJA_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jPanel1.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 530, 80));

        jPanel37.setBackground(new java.awt.Color(6, 10, 28));
        jPanel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel37.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("KARDES DE PRODUCTOS");
        jLabel68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel68MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel68MouseExited(evt);
            }
        });
        jPanel37.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        ESTRELLA_33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_launch_30px_3.png"))); // NOI18N
        jPanel37.add(ESTRELLA_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 40, 40));

        HOJA_35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ALMACENV1/src/IMAGENES/icons8_turtle_30px_3.png"))); // NOI18N
        jPanel37.add(HOJA_35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 40, 40));

        jPanel1.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 800, 530, 80));

        jPanel36.setBackground(new java.awt.Color(6, 10, 28));
        jPanel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel36.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("ACTUALIZAR PRECIO DE VENTA");
        jLabel67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel67MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel67MouseExited(evt);
            }
        });
        jPanel36.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        ESTRELLA_32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px_2.png"))); // NOI18N
        jPanel36.add(ESTRELLA_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 30, 30));

        HOJA_34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_cactus_40px.png"))); // NOI18N
        jPanel36.add(HOJA_34, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 50, 50));

        jPanel1.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 880, 530, 80));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jLabel58MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseEntered
       // jLabel58.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel58MouseEntered

    private void jLabel58MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseExited
        //jLabel58.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel58MouseExited

    private void jLabel40MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseEntered
        //jLabel40.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel40MouseEntered

    private void jLabel40MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseExited
        //jLabel40.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel40MouseExited

    private void jLabel59MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseEntered
        //jLabel59.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel59MouseEntered

    private void jLabel59MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseExited
        //jLabel59.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel59MouseExited

    private void jLabel60MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseEntered
        //jLabel60.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel60MouseEntered

    private void jLabel60MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseExited
        //jLabel60.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel60MouseExited

    private void jLabel61MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseEntered
        //jLabel61.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel61MouseEntered

    private void jLabel61MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseExited
        //jLabel61.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel61MouseExited

    private void jLabel62MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseEntered
        //jLabel62.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel62MouseEntered

    private void jLabel62MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseExited
        //jLabel62.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel62MouseExited

    private void jLabel63MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseEntered
        //jLabel63.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel63MouseEntered

    private void jLabel63MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseExited
        //jLabel63.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel63MouseExited

    private void jLabel64MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseEntered
        //jLabel64.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel64MouseEntered

    private void jLabel64MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseExited
        //jLabel64.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel64MouseExited

    private void jLabel65MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseEntered
        //jLabel65.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel65MouseEntered

    private void jLabel65MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseExited
        //jLabel65.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel65MouseExited

    private void jLabel66MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseEntered
        //jLabel66.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel66MouseEntered

    private void jLabel66MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseExited
        //jLabel66.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel66MouseExited

    private void jLabel68MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel68MouseEntered
        //jLabel68.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel68MouseEntered

    private void jLabel68MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel68MouseExited
        //jLabel68.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel68MouseExited

    private void jLabel67MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel67MouseEntered
        //jLabel67.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel67MouseEntered

    private void jLabel67MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel67MouseExited
        //jLabel67.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel67MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ESTRELLA_27;
    private javax.swing.JLabel ESTRELLA_28;
    private javax.swing.JLabel ESTRELLA_29;
    private javax.swing.JLabel ESTRELLA_30;
    private javax.swing.JLabel ESTRELLA_31;
    private javax.swing.JLabel ESTRELLA_32;
    private javax.swing.JLabel ESTRELLA_33;
    private javax.swing.JLabel HOJA_21;
    private javax.swing.JLabel HOJA_28;
    private javax.swing.JLabel HOJA_29;
    private javax.swing.JLabel HOJA_30;
    private javax.swing.JLabel HOJA_31;
    private javax.swing.JLabel HOJA_32;
    private javax.swing.JLabel HOJA_33;
    private javax.swing.JLabel HOJA_34;
    private javax.swing.JLabel HOJA_35;
    private javax.swing.JLabel estrella_13;
    private javax.swing.JLabel estrella_14;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
