/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOME;

import Producto.*;
import HOME.*;
import ALMACEN.CrearBodegas;
import Producto.CrearProducto;
import Producto.FAMILIA1;
import Producto.FAMILIA2;
import Producto.FAMILIA3;
import Producto.UNDMEDIDA;
import USUARIO.Usuario;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
import AppPackage.AnimationClass;//Acá importé la librería para los nombres desplazables de los botones
import CLASS.GENERAL_CLASS;
import HOME.*;
import java.awt.Dimension;
import desplazable.Desface;//ACÁ IMPORTÉ LA LIBRERÍA PARA EL MENÚ DESPLAZABLE DE LA DERECHA
import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author Edwin
 */
public class Startt extends javax.swing.JFrame {

    Desface desplace;// ACÁ INSTANCIÉ EL COMPONENTE de la libreria desplazable

    /**
     * Creates new form Startt
     */
    public Startt(FAMILIA1 WinFm1,FAMILIA2 WinFm2,FAMILIA3 WinFm3,UNDMEDIDA WindFnidad,CrearBodegas WinCrearBG,Usuario WinUser,Configuracion WinConf,CrearProducto win) {
        
        initComponents();
       // HomePrincipal.setVisible(false);
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton(evt);
            }
        });
        boton.setSize(81,30);
        boton.setVisible(true);
//        this.BarraSuperio.add(boton);
        WinFm1_1 =WinFm1;
            WinFm2_1= WinFm2 ;
            WinFm3_1  =WinFm3;
            WindFnidad_1 =WindFnidad ;
            WinCrearBG_1  =WinCrearBG;
            WinUser_1 =WinUser ;
            WinConf_1=WinConf;
            CrearProducto =win;
     
    }

    public Startt() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HomePrincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BTN_BUSCAR = new javax.swing.JButton();
        BOX_BUSCAR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        logo_claro = new javax.swing.JLabel();
        logo_oscuro = new javax.swing.JLabel();
        BOX_BUSCAR1 = new javax.swing.JTextField();
        BOX_BUSCAR2 = new javax.swing.JTextField();
        BOX_BUSCAR3 = new javax.swing.JTextField();
        BOX_BUSCAR4 = new javax.swing.JTextField();
        BTN_MENU = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(7, 16, 19));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        HomePrincipal.setBackground(new java.awt.Color(10, 15, 42));
        HomePrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HomePrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("STXinwei", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kardex Producto");
        HomePrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 200, 30));

        BTN_BUSCAR.setBackground(new java.awt.Color(11, 24, 29));
        BTN_BUSCAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_BUSCAR.setText("BUSCAR");
        BTN_BUSCAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_BUSCAR.setOpaque(false);
        BTN_BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BUSCARActionPerformed(evt);
            }
        });
        HomePrincipal.add(BTN_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 90, 40));

        BOX_BUSCAR.setBackground(new java.awt.Color(16, 34, 43));
        BOX_BUSCAR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BOX_BUSCAR.setForeground(new java.awt.Color(255, 255, 255));
        BOX_BUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOX_BUSCARMouseClicked(evt);
            }
        });
        HomePrincipal.add(BOX_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 510, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jetxcel");
        HomePrincipal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 50));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_10px.png"))); // NOI18N
        HomePrincipal.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px.png"))); // NOI18N
        HomePrincipal.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 30, 30));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_10px_1.png"))); // NOI18N
        HomePrincipal.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 20, 20));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_32px.png"))); // NOI18N
        HomePrincipal.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_launch_30px_3.png"))); // NOI18N
        HomePrincipal.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 160, 40, 40));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_32px.png"))); // NOI18N
        HomePrincipal.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 210, -1, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_rocket_40px.png"))); // NOI18N
        HomePrincipal.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 50, 50));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px_2.png"))); // NOI18N
        HomePrincipal.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_starfish_20px_2.png"))); // NOI18N
        HomePrincipal.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 30, 30));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_astronaut_40px_1.png"))); // NOI18N
        HomePrincipal.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, 50));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_asteroid_50px_4.png"))); // NOI18N
        HomePrincipal.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 60, 50));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_shooting_stars_50px_1.png"))); // NOI18N
        HomePrincipal.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 60));

        logo_claro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_rocket_take_off_50px.png"))); // NOI18N
        HomePrincipal.add(logo_claro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        logo_oscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_rocket_take_off_50px_1.png"))); // NOI18N
        HomePrincipal.add(logo_oscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        BOX_BUSCAR1.setBackground(new java.awt.Color(16, 34, 43));
        BOX_BUSCAR1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BOX_BUSCAR1.setForeground(new java.awt.Color(255, 255, 255));
        BOX_BUSCAR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOX_BUSCAR1MouseClicked(evt);
            }
        });
        HomePrincipal.add(BOX_BUSCAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        BOX_BUSCAR2.setBackground(new java.awt.Color(16, 34, 43));
        BOX_BUSCAR2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BOX_BUSCAR2.setForeground(new java.awt.Color(255, 255, 255));
        BOX_BUSCAR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOX_BUSCAR2MouseClicked(evt);
            }
        });
        HomePrincipal.add(BOX_BUSCAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 600, 30));

        BOX_BUSCAR3.setBackground(new java.awt.Color(16, 34, 43));
        BOX_BUSCAR3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BOX_BUSCAR3.setForeground(new java.awt.Color(255, 255, 255));
        BOX_BUSCAR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOX_BUSCAR3MouseClicked(evt);
            }
        });
        HomePrincipal.add(BOX_BUSCAR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 130, 30));

        BOX_BUSCAR4.setBackground(new java.awt.Color(16, 34, 43));
        BOX_BUSCAR4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BOX_BUSCAR4.setForeground(new java.awt.Color(255, 255, 255));
        BOX_BUSCAR4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOX_BUSCAR4MouseClicked(evt);
            }
        });
        HomePrincipal.add(BOX_BUSCAR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 130, 30));

        BTN_MENU.setForeground(new java.awt.Color(255, 255, 255));
        BTN_MENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Menu_tres_lineas.png"))); // NOI18N
        BTN_MENU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_MENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_MENUMouseClicked(evt);
            }
        });
        HomePrincipal.add(BTN_MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estadisticas");
        HomePrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jScrollPane1.setViewportView(HomePrincipal);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 1198, 631));

        jPanel3.setBackground(new java.awt.Color(7, 16, 19));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(7, 16, 19));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Estadisticos_42px.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 40));

        jButton3.setBackground(new java.awt.Color(7, 16, 19));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/AAgregar_Usuario.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 40, 40));

        jButton4.setBackground(new java.awt.Color(7, 16, 19));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Money_42PX.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 40, 40));

        jButton5.setBackground(new java.awt.Color(7, 16, 19));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Bodega_42Px.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 40, 40));

        jButton6.setBackground(new java.awt.Color(7, 16, 19));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Producto_New_32Px.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 40, 40));

        jButton7.setBackground(new java.awt.Color(7, 16, 19));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Resumen.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton7AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 40, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 617));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1291, 701));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BOX_BUSCAR4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOX_BUSCAR4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_BUSCAR4MouseClicked

    private void BOX_BUSCAR3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOX_BUSCAR3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_BUSCAR3MouseClicked

    private void BOX_BUSCAR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOX_BUSCAR2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_BUSCAR2MouseClicked

    private void BOX_BUSCAR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOX_BUSCAR1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_BUSCAR1MouseClicked

    private void BOX_BUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOX_BUSCARMouseClicked

    }//GEN-LAST:event_BOX_BUSCARMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
             // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
      // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    private void BTN_MENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MENUMouseClicked
        //SALE EL MENÚ PRUEBA LATERAL HACIA LA IZQUIERDA
     /*   if (Menu_deslizable_Panel_Contenedor_Botones.getX() == 110) {
            desplace.desplazarIzquierda(Menu_deslizable_Panel_Contenedor_Botones, Menu_deslizable_Panel_Contenedor_Botones.getX(), 0, 10, 10);
        } else if (Menu_deslizable_Panel_Contenedor_Botones.getX() == 0) {
            desplace.desplazarDerecha(Menu_deslizable_Panel_Contenedor_Botones, Menu_deslizable_Panel_Contenedor_Botones.getX(), 110, 10, 10);
        }*/
    }//GEN-LAST:event_BTN_MENUMouseClicked
    private void Boton(java.awt.event.ActionEvent evt){
       HomePrincipal.setVisible(true);
        this.add(HomePrincipal);
        
    }
    private void BTN_BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BUSCARActionPerformed
        //general.OpenWindows(WinUser_1, jPanel1);
      
      
       // TODO add your handling code here:
    }//GEN-LAST:event_BTN_BUSCARActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        //-----> SALIDA HACIA LA DERECHA DE TEXTO ESTADISTICOS
        Color Estadísticos_Azúl = new Color(54, 81, 207);
        jButton2.setBackground(Estadísticos_Azúl);
        AnimationClass ESTADISTICOS = new AnimationClass();//ESTADISTICOS
       // ESTADISTICOS.jLabelXLeft(-100, 20, 5, 8, txt_Estadisticos);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        //<----- ENTRADA HACIA LA IZQUIERDA DE TEXTO ESTADISTICOS
        jButton2.setBackground(null);
        AnimationClass ESTADISTICOSS = new AnimationClass();//ESTADISTICOS
      //  ESTADISTICOSS.jLabelXLeft(20, -100, 5, 8, txt_Estadisticos);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        //-----> SALIDA HACIA LA DERECHA EL TEXTO DE AGREGAR USUARIO
        Color AG_USUARIOS_AZUL = new Color(54, 81, 207);
        jButton3.setBackground(AG_USUARIOS_AZUL);
        AnimationClass AG_USUARIOS = new AnimationClass();//USUARIOS
      //  AG_USUARIOS.jLabelXLeft(-100, 20, 5, 8, txt_Ag_Usuario);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        //<----- ENTRADA HACIA LA IZQUIERDA EL TEXTO DE AGREGAR USUARIO
        jButton3.setBackground(null);
        AnimationClass AG_USUARIOSS = new AnimationClass();//ESTADISTICOS
    //    AG_USUARIOSS.jLabelXLeft(20, -100, 5, 8, txt_Ag_Usuario);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        general.OpenWindows(WinUser_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        general.OpenWindows(WindFnidad_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        //-----> SALIDA HACIA LA DERECHA DE EL TEXTO DE VENTAS
        Color Color_Ventas_Azul = new Color(54, 81, 207);
        jButton4.setBackground(Color_Ventas_Azul);
        AnimationClass VENTAS = new AnimationClass();//VENTAS
      //  VENTAS.jLabelXLeft(-100, 20, 5, 8, txt_Ventas);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        //<----- ENTRADA HACIA LA IZQUIERDA DE EL TEXTO DE VENTAS
        jButton4.setBackground(null);
        AnimationClass VENTASS = new AnimationClass();//VENTAS
       // VENTASS.jLabelXLeft(20, -100, 5, 8, txt_Ventas);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        general.OpenWindows(WinCrearBG_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        //-----> SALIDA HACIA LA DERECHA DE EL TEXTO DE BODEGA
        Color BODE_COLOR_AZUL = new Color(54, 81, 207);
        jButton5.setBackground(BODE_COLOR_AZUL);
        AnimationClass BODEGA = new AnimationClass();//BODEGA
    //    BODEGA.jLabelXLeft(-100, 20, 5, 8, txt_bodega);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS//
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        //<----- ENTRADA HACIA LA IZQUIERDA DE EL TEXTO DE BODEGA
        jButton5.setBackground(null);
        AnimationClass BODEGAA = new AnimationClass();//BODEGA
       // BODEGAA.jLabelXLeft(20, -100, 5, 8, txt_bodega);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS//
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        general.OpenWindows(CrearProducto, null);
        CrearProducto.InicioProducto();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        //-----> SALIDA HACIA LA DERECHA DE EL TEXTO PRODUCTO
        Color PRODUCTO_COLOR_AZUL = new Color(54, 81, 207);
        jButton6.setBackground(PRODUCTO_COLOR_AZUL);
        AnimationClass PRODUCTO = new AnimationClass();//PRODUCTO
     //   PRODUCTO.jLabelXLeft(-100, 20, 5, 8, txt_Producto);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS//
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        //<----- SALIDA HACIA LA IZQUIERDA DE EL TEXTO DE PRODUCTO
        jButton6.setBackground(null);
        AnimationClass PRODUCTOO = new AnimationClass();//PRODUCTO
      //  PRODUCTOO.jLabelXLeft(20, -100, 5, 8, txt_Producto);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS//
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton7AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7AncestorAdded

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        //ABRIR LA VENTANA DE INFORMES

    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        //-----> SALIDA HACIA LA DERECHA DE EL TEXTO INFORMES
        Color INFORMES_COLOR_AZUL = new Color(54, 81, 207);
        jButton7.setBackground(INFORMES_COLOR_AZUL);
        AnimationClass INFORME = new AnimationClass();//INFORMES
       // INFORME.jLabelXLeft(-100, 20, 5, 8, txt_Informes);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS//
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        //<----- SALIDA HACIA LA IZQUIERDA DE EL TEXTO INFORMES
        jButton7.setBackground(null);
        AnimationClass INFORMEE = new AnimationClass();//INFORMES
       // INFORMEE.jLabelXLeft(20, -100, 5, 8, txt_Informes);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS//
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startt().setVisible(true);
            }
        });
    }
    JButton boton  = new JButton ("Home +"); 
    public GENERAL_CLASS general = new GENERAL_CLASS();
  private int XY []={0,0};
        public  FAMILIA1 WinFm1_1;
        public  FAMILIA2 WinFm2_1  ;
        public  FAMILIA3 WinFm3_1  ;
        public  UNDMEDIDA WindFnidad_1 ;
        public  CrearBodegas WinCrearBG_1  ;
        public  Usuario WinUser_1 ;
        public  Configuracion WinConf_1;
        public  CrearProducto CrearProducto;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BOX_BUSCAR;
    private javax.swing.JTextField BOX_BUSCAR1;
    private javax.swing.JTextField BOX_BUSCAR2;
    private javax.swing.JTextField BOX_BUSCAR3;
    private javax.swing.JTextField BOX_BUSCAR4;
    private javax.swing.JButton BTN_BUSCAR;
    private javax.swing.JLabel BTN_MENU;
    private javax.swing.JPanel HomePrincipal;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_claro;
    private javax.swing.JLabel logo_oscuro;
    // End of variables declaration//GEN-END:variables
}
