/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOME;

import ALMACEN.CREARITEM.CrearBodegas;
import ALMACEN.CREARITEM.CrearProducto;
import ALMACEN.CREARITEM.FAMILIA1;
import ALMACEN.CREARITEM.FAMILIA2;
import ALMACEN.CREARITEM.FAMILIA3;
import ALMACEN.CREARITEM.UNDMEDIDA;
import ALMACEN.Usuario;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
import AppPackage.AnimationClass;//Acá importé la librería para los nombres desplazables de los botones
import CLASS.GENERAL_CLASS;
import  HOME.*;
import java.awt.Dimension;
import desplazable.Desface;//ACÁ IMPORTÉ LA LIBRERÍA PARA EL MENÚ DESPLAZABLE DE LA DERECHA
import javax.swing.JPanel;

/**
 *
 * @author Edwin
 */
public class Startt extends javax.swing.JFrame {

    Desface desplace;// ACÁ INSTANCIÉ EL COMPONENTE de la libreria desplazable
    

    /**
     * Creates new form Startt
     * @param WinFm1
     * @param WinFm2
     * @param WinFm3
     * @param WindFnidad
     * @param WinCrearBG
     * @param WinUser
     * @param WinConf
     */
    public Startt(FAMILIA1 WinFm1,FAMILIA2 WinFm2,FAMILIA3 WinFm3,UNDMEDIDA WindFnidad,CrearBodegas WinCrearBG,Usuario WinUser,Configuracion WinConf,CrearProducto win) {
        initComponents();
            WinFm1_1 =WinFm1;
            WinFm2_1= WinFm2 ;
            WinFm3_1  =WinFm3;
            WindFnidad_1 =WindFnidad ;
            WinCrearBG_1  =WinCrearBG;
            WinUser_1 =WinUser ;
            WinConf_1=WinConf;
            CrearProducto =win;
        desplace = new Desface();// ESTA TAMBIÉN ES DEL MENÚ DESPLAZABLE
        setExtendedState(MAXIMIZED_BOTH);//ACÁ MAXIMIZA LA VENTANA PRINCIPAL
        BTN_MODO_NOCHE.setEnabled(false);//DESACTIVA EL BOTON MODO OSCURO
        TXT_NOCHE.setEnabled(false);//DESACTIVA EL TEXTO MODO OSCURO
        BTN_MODO_NOCHE.setVisible(false);//OCULTA EL BOTON MODO OSCURO
        TXT_NOCHE.setVisible(false);//OCULTA EL TEXTO MODO OSCURO
        setExtendedState(MAXIMIZED_BOTH);//ACÁ MAXIMIZA LA VENTANA PRINCIPAL
        JButton[] btns = {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7};
        for (JButton btn : btns) {
            btn.setBackground(new Color(21, 25, 28));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {
                }

                @Override
                public void mousePressed(MouseEvent me) {

                }

                @Override
                public void mouseReleased(MouseEvent me) {

                }

                @Override
                public void mouseEntered(MouseEvent me) {
                    //btn.setBackground(new Color(54, 81, 207));
                }

                @Override
                public void mouseExited(MouseEvent me) {
                    //btn.setBackground(new Color(21, 25, 28));

                }
            });
        }
    }

    private Startt() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Menu_Lateral_Izquierdo = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Contenedor_Licencia = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txt_Licencia = new javax.swing.JLabel();
        BTN_MODO_NOCHE = new javax.swing.JLabel();
        TXT_NOCHE = new javax.swing.JLabel();
        TXT_DIA = new javax.swing.JLabel();
        BTN_MODO_DIA = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Menu_Central = new javax.swing.JPanel();
        txt_Estadisticos = new javax.swing.JLabel();
        txt_Ag_Usuario = new javax.swing.JLabel();
        txt_Ventas = new javax.swing.JLabel();
        txt_bodega = new javax.swing.JLabel();
        txt_Producto = new javax.swing.JLabel();
        txt_Informes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BTN_MENU = new javax.swing.JLabel();
        Menu_deslizable_Panel_Contenedor_Botones = new javax.swing.JPanel();
        txt_CONFIGURACION = new javax.swing.JLabel();
        txt_CHATBOT = new javax.swing.JLabel();
        txt_BUSQUEDA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(34, 40, 44));

        Menu_Lateral_Izquierdo.setBackground(new java.awt.Color(21, 25, 28));
        Menu_Lateral_Izquierdo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(34, 40, 44));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Estadisticos_42px.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        Menu_Lateral_Izquierdo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 40, 40));

        jButton3.setBackground(new java.awt.Color(34, 40, 44));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/AAgregar_Usuario.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Menu_Lateral_Izquierdo.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, 40, 40));

        jButton4.setBackground(new java.awt.Color(34, 40, 44));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Money_42PX.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        Menu_Lateral_Izquierdo.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, 40, 40));

        jButton5.setBackground(new java.awt.Color(34, 40, 44));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Bodega_42Px.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        Menu_Lateral_Izquierdo.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 240, 40, 40));

        jButton6.setBackground(new java.awt.Color(34, 40, 44));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Producto_New_32Px.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        Menu_Lateral_Izquierdo.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 290, 40, 40));

        jButton7.setBackground(new java.awt.Color(34, 40, 44));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Resumen.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton7AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Menu_Lateral_Izquierdo.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 340, 40, 40));
        Menu_Lateral_Izquierdo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 50, 10));
        Menu_Lateral_Izquierdo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 10));
        Menu_Lateral_Izquierdo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 10));

        Contenedor_Licencia.setBackground(new java.awt.Color(21, 25, 28));
        Contenedor_Licencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Contenedor_LicenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Contenedor_LicenciaMouseExited(evt);
            }
        });
        Contenedor_Licencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(34, 40, 44));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Licencia_32PX.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        Contenedor_Licencia.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 40, 50));

        Menu_Lateral_Izquierdo.add(Contenedor_Licencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 70, 60));

        txt_Licencia.setForeground(new java.awt.Color(255, 255, 255));
        txt_Licencia.setText("LICENCIA");
        Menu_Lateral_Izquierdo.add(txt_Licencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 590, -1, -1));

        BTN_MODO_NOCHE.setBackground(new java.awt.Color(64, 64, 64));
        BTN_MODO_NOCHE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_night_32px.png"))); // NOI18N
        BTN_MODO_NOCHE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_MODO_NOCHE.setOpaque(true);
        BTN_MODO_NOCHE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_MODO_NOCHEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN_MODO_NOCHEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN_MODO_NOCHEMouseExited(evt);
            }
        });
        Menu_Lateral_Izquierdo.add(BTN_MODO_NOCHE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 463, -1, -1));

        TXT_NOCHE.setBackground(new java.awt.Color(21, 25, 28));
        TXT_NOCHE.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        TXT_NOCHE.setForeground(new java.awt.Color(255, 255, 255));
        TXT_NOCHE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TXT_NOCHE.setText("A NOCHE");
        TXT_NOCHE.setOpaque(true);
        Menu_Lateral_Izquierdo.add(TXT_NOCHE, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 500, 60, 20));

        TXT_DIA.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        TXT_DIA.setForeground(new java.awt.Color(255, 255, 255));
        TXT_DIA.setText(" A DIA");
        Menu_Lateral_Izquierdo.add(TXT_DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 500, 40, 20));

        BTN_MODO_DIA.setBackground(new java.awt.Color(21, 25, 28));
        BTN_MODO_DIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_sun_32px.png"))); // NOI18N
        BTN_MODO_DIA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_MODO_DIA.setOpaque(true);
        BTN_MODO_DIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_MODO_DIAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN_MODO_DIAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN_MODO_DIAMouseExited(evt);
            }
        });
        Menu_Lateral_Izquierdo.add(BTN_MODO_DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 463, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CAMBIAR");
        Menu_Lateral_Izquierdo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        Menu_Central.setBackground(new java.awt.Color(34, 40, 44));
        Menu_Central.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Menu_Central.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Estadisticos.setBackground(new java.awt.Color(34, 40, 44));
        txt_Estadisticos.setForeground(new java.awt.Color(255, 255, 255));
        txt_Estadisticos.setText("ESTADÍSTICOS");
        txt_Estadisticos.setOpaque(true);
        Menu_Central.add(txt_Estadisticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 31, -1, -1));

        txt_Ag_Usuario.setBackground(new java.awt.Color(34, 40, 44));
        txt_Ag_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_Ag_Usuario.setText("+ USUARIO");
        txt_Ag_Usuario.setOpaque(true);
        Menu_Central.add(txt_Ag_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 150, -1, -1));

        txt_Ventas.setBackground(new java.awt.Color(34, 40, 44));
        txt_Ventas.setForeground(new java.awt.Color(255, 255, 255));
        txt_Ventas.setText("VENTAS");
        txt_Ventas.setOpaque(true);
        Menu_Central.add(txt_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 200, -1, -1));

        txt_bodega.setBackground(new java.awt.Color(34, 40, 44));
        txt_bodega.setForeground(new java.awt.Color(255, 255, 255));
        txt_bodega.setText("BODEGA");
        txt_bodega.setOpaque(true);
        Menu_Central.add(txt_bodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 250, -1, -1));

        txt_Producto.setBackground(new java.awt.Color(34, 40, 44));
        txt_Producto.setForeground(new java.awt.Color(255, 255, 255));
        txt_Producto.setText("+ PRODUCTO");
        txt_Producto.setOpaque(true);
        Menu_Central.add(txt_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 300, -1, -1));

        txt_Informes.setBackground(new java.awt.Color(34, 40, 44));
        txt_Informes.setForeground(new java.awt.Color(255, 255, 255));
        txt_Informes.setText("INFORMES");
        txt_Informes.setOpaque(true);
        Menu_Central.add(txt_Informes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Estadísticos de Ventas");
        Menu_Central.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("__________________________________________________");
        Menu_Central.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/estadistico de escritorio.jpg"))); // NOI18N
        Menu_Central.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 610, 390));

        jLabel6.setBackground(new java.awt.Color(34, 40, 44));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MINIMIZAR");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        Menu_Central.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, -1));

        jLabel7.setBackground(new java.awt.Color(34, 40, 44));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MAXIMIZAR");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        Menu_Central.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, -1, -1));

        jLabel8.setBackground(new java.awt.Color(34, 40, 44));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CERRAR");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        Menu_Central.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, -1));

        jLabel9.setBackground(new java.awt.Color(34, 40, 44));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("REDIMENCIONAR");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        Menu_Central.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_MENU.setForeground(new java.awt.Color(255, 255, 255));
        BTN_MENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Menu_tres_lineas.png"))); // NOI18N
        BTN_MENU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_MENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_MENUMouseClicked(evt);
            }
        });
        jPanel3.add(BTN_MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Menu_deslizable_Panel_Contenedor_Botones.setBackground(new java.awt.Color(51, 0, 51));
        Menu_deslizable_Panel_Contenedor_Botones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_CONFIGURACION.setBackground(new java.awt.Color(51, 0, 51));
        txt_CONFIGURACION.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_CONFIGURACION.setForeground(new java.awt.Color(255, 255, 255));
        txt_CONFIGURACION.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_CONFIGURACION.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Configuraciones_42Px.png"))); // NOI18N
        txt_CONFIGURACION.setText("AJUSTES");
        txt_CONFIGURACION.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_CONFIGURACION.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_CONFIGURACION.setOpaque(true);
        txt_CONFIGURACION.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txt_CONFIGURACION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_CONFIGURACIONMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_CONFIGURACIONMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_CONFIGURACIONMouseExited(evt);
            }
        });
        Menu_deslizable_Panel_Contenedor_Botones.add(txt_CONFIGURACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 30, 70, -1));

        txt_CHATBOT.setBackground(new java.awt.Color(51, 0, 51));
        txt_CHATBOT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_CHATBOT.setForeground(new java.awt.Color(255, 255, 255));
        txt_CHATBOT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_CHATBOT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Chat_Bot.png"))); // NOI18N
        txt_CHATBOT.setText("CHAT BOT");
        txt_CHATBOT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_CHATBOT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_CHATBOT.setOpaque(true);
        txt_CHATBOT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txt_CHATBOT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_CHATBOTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_CHATBOTMouseExited(evt);
            }
        });
        Menu_deslizable_Panel_Contenedor_Botones.add(txt_CHATBOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 180, 70, 70));

        txt_BUSQUEDA.setBackground(new java.awt.Color(51, 0, 51));
        txt_BUSQUEDA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_BUSQUEDA.setForeground(new java.awt.Color(255, 255, 255));
        txt_BUSQUEDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_BUSQUEDA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Buscar_32px.png"))); // NOI18N
        txt_BUSQUEDA.setText("BUSCAR");
        txt_BUSQUEDA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_BUSQUEDA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_BUSQUEDA.setOpaque(true);
        txt_BUSQUEDA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txt_BUSQUEDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_BUSQUEDAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_BUSQUEDAMouseExited(evt);
            }
        });
        Menu_deslizable_Panel_Contenedor_Botones.add(txt_BUSQUEDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 310, 70, 60));

        jPanel3.add(Menu_deslizable_Panel_Contenedor_Botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 76, 460));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu_Lateral_Izquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu_Central, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_Lateral_Izquierdo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Menu_Central, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1316, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        //-----> SALIDA HACIA LA DERECHA DE TEXTO ESTADISTICOS
        Color Estadísticos_Azúl = new Color(54, 81, 207);
        jButton2.setBackground(Estadísticos_Azúl);
        AnimationClass ESTADISTICOS = new AnimationClass();//ESTADISTICOS
        ESTADISTICOS.jLabelXLeft(-100, 20, 5, 8, txt_Estadisticos);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        //<----- ENTRADA HACIA LA IZQUIERDA DE TEXTO ESTADISTICOS
        jButton2.setBackground(null);
        AnimationClass ESTADISTICOSS = new AnimationClass();//ESTADISTICOS
        ESTADISTICOSS.jLabelXLeft(20, -100, 5, 8, txt_Estadisticos);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        //-----> SALIDA HACIA LA DERECHA EL TEXTO DE AGREGAR USUARIO
        Color AG_USUARIOS_AZUL = new Color(54, 81, 207);
        jButton3.setBackground(AG_USUARIOS_AZUL);
        AnimationClass AG_USUARIOS = new AnimationClass();//USUARIOS
        AG_USUARIOS.jLabelXLeft(-100, 20, 5, 8, txt_Ag_Usuario);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        //<----- ENTRADA HACIA LA IZQUIERDA EL TEXTO DE AGREGAR USUARIO
        jButton3.setBackground(null);
        AnimationClass AG_USUARIOSS = new AnimationClass();//ESTADISTICOS
        AG_USUARIOSS.jLabelXLeft(20, -100, 5, 8, txt_Ag_Usuario);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        //-----> SALIDA HACIA LA DERECHA DE EL TEXTO DE VENTAS
        Color Color_Ventas_Azul = new Color(54, 81, 207);
        jButton4.setBackground(Color_Ventas_Azul);
        AnimationClass VENTAS = new AnimationClass();//VENTAS
        VENTAS.jLabelXLeft(-100, 20, 5, 8, txt_Ventas);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        //<----- ENTRADA HACIA LA IZQUIERDA DE EL TEXTO DE VENTAS
        jButton4.setBackground(null);
        AnimationClass VENTASS = new AnimationClass();//VENTAS
        VENTASS.jLabelXLeft(20, -100, 5, 8, txt_Ventas);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        //-----> SALIDA HACIA LA DERECHA DE EL TEXTO DE BODEGA
        Color BODE_COLOR_AZUL = new Color(54, 81, 207);
        jButton5.setBackground(BODE_COLOR_AZUL);
        AnimationClass BODEGA = new AnimationClass();//BODEGA
        BODEGA.jLabelXLeft(-100, 20, 5, 8, txt_bodega);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS// 
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        //<----- ENTRADA HACIA LA IZQUIERDA DE EL TEXTO DE BODEGA
        jButton5.setBackground(null);
        AnimationClass BODEGAA = new AnimationClass();//BODEGA
        BODEGAA.jLabelXLeft(20, -100, 5, 8, txt_bodega);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS// 
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        //-----> SALIDA HACIA LA DERECHA DE EL TEXTO PRODUCTO
        Color PRODUCTO_COLOR_AZUL = new Color(54, 81, 207);
        jButton6.setBackground(PRODUCTO_COLOR_AZUL);
        AnimationClass PRODUCTO = new AnimationClass();//PRODUCTO
        PRODUCTO.jLabelXLeft(-100, 20, 5, 8, txt_Producto);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS// 
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        //<----- SALIDA HACIA LA IZQUIERDA DE EL TEXTO DE PRODUCTO
        jButton6.setBackground(null);
        AnimationClass PRODUCTOO = new AnimationClass();//PRODUCTO
        PRODUCTOO.jLabelXLeft(20, -100, 5, 8, txt_Producto);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS// 
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        //-----> SALIDA HACIA LA DERECHA DE EL TEXTO INFORMES
        Color INFORMES_COLOR_AZUL = new Color(54, 81, 207);
        jButton7.setBackground(INFORMES_COLOR_AZUL);
        AnimationClass INFORME = new AnimationClass();//INFORMES
        INFORME.jLabelXLeft(-100, 20, 5, 8, txt_Informes);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS// 
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        //<----- SALIDA HACIA LA IZQUIERDA DE EL TEXTO INFORMES
        jButton7.setBackground(null);
        AnimationClass INFORMEE = new AnimationClass();//INFORMES
        INFORMEE.jLabelXLeft(20, -100, 5, 8, txt_Informes);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS//
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        //-----> SALIDA HACIA ABAJO EL TEXTO LICENCIA
        Color LICENCIA_COLOR_AZUL = new Color(54, 81, 207);
        jButton1.setBackground(LICENCIA_COLOR_AZUL);
        AnimationClass LICENCIA = new AnimationClass();//LICENCIA
        LICENCIA.jLabelYDown(590, 610, 5, 10, txt_Licencia);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS// 

    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        //-----> ENTRADA HACIA ARRIBA EL TEXTO LICENCIA
        jButton1.setBackground(null);
        AnimationClass LICENCIAA = new AnimationClass();//LICENCIA
        LICENCIAA.jLabelYUp(610, 590, 5, 10, txt_Licencia);//(Posición Actual, Posición futura, velocidad, velocidad, nombre del objeto)// MUESTRA EL TEXTO DE ESTADISTICOS// 

    }//GEN-LAST:event_jButton1MouseExited

    private void Contenedor_LicenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contenedor_LicenciaMouseExited

    }//GEN-LAST:event_Contenedor_LicenciaMouseExited

    private void Contenedor_LicenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contenedor_LicenciaMouseEntered

    }//GEN-LAST:event_Contenedor_LicenciaMouseEntered

    private void BTN_MENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MENUMouseClicked
            //SALE EL MENÚ PRUEBA LATERAL HACIA LA IZQUIERDA 
        if (Menu_deslizable_Panel_Contenedor_Botones.getX() == 110) {
            desplace.desplazarIzquierda(Menu_deslizable_Panel_Contenedor_Botones, Menu_deslizable_Panel_Contenedor_Botones.getX(), 0, 10, 10);
        } else if (Menu_deslizable_Panel_Contenedor_Botones.getX() == 0) {
            desplace.desplazarDerecha(Menu_deslizable_Panel_Contenedor_Botones, Menu_deslizable_Panel_Contenedor_Botones.getX(), 110, 10, 10);
        }

    }//GEN-LAST:event_BTN_MENUMouseClicked

    private void txt_CONFIGURACIONMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CONFIGURACIONMouseEntered
        Color COLOR_AZUL_OSCURO = new Color(0, 0, 102);
        txt_CONFIGURACION.setBackground(COLOR_AZUL_OSCURO);

    }//GEN-LAST:event_txt_CONFIGURACIONMouseEntered

    private void txt_CONFIGURACIONMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CONFIGURACIONMouseExited
        txt_CONFIGURACION.setBackground(null);

    }//GEN-LAST:event_txt_CONFIGURACIONMouseExited

    private void txt_BUSQUEDAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_BUSQUEDAMouseEntered
        Color COLOR_AZUL_OSCURO = new Color(0, 0, 102);
        txt_BUSQUEDA.setBackground(COLOR_AZUL_OSCURO);
    }//GEN-LAST:event_txt_BUSQUEDAMouseEntered

    private void txt_CHATBOTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CHATBOTMouseExited
        txt_CHATBOT.setBackground(null);
    }//GEN-LAST:event_txt_CHATBOTMouseExited

    private void txt_BUSQUEDAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_BUSQUEDAMouseExited
        txt_BUSQUEDA.setBackground(null);
    }//GEN-LAST:event_txt_BUSQUEDAMouseExited

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
      // general.OpenWindows(WinUser_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    public void ActivarModosClort(boolean x){
            BTN_MODO_DIA.setEnabled(x);
        BTN_MODO_DIA.setVisible(x);
        TXT_DIA.setEnabled(x);
        TXT_DIA.setVisible(x);
        BTN_MODO_NOCHE.setVisible(!x);
        BTN_MODO_NOCHE.setEnabled(!x);
        TXT_NOCHE.setVisible(!x);
    }
    private void BTN_MODO_NOCHEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MODO_NOCHEMouseClicked

        //PARA PASAR A MODO OSCURO 
        jButton1.setBackground(null);
        jButton2.setBackground(null);
        jButton3.setBackground(null);
        jButton4.setBackground(null);
        jButton5.setBackground(null);
        jButton6.setBackground(null);
        jButton7.setBackground(null);
        ActivarModosClort(true);
        //PARA PASAR A MODO OSCURO 

        Color Menu_Izquierdo_Oscuro = new Color(21, 25, 28);//CAMBIA AL COLOR ORIGINAL EL MENÚ LATERAL IZQUIERDO
        Color Menu_Central_Oscuro = new Color(34, 40, 44);
        Color Menu_De_Fondo_Oscuro = new Color(34, 40, 44);
        Color Menu_Lateral_Derecho_Oscuro = new Color(51, 0, 51);
        Color Contenedor_btnLicencia_Oscuro = new Color(21, 25, 28);
        Color ColorOscuro_txt_Modo_Oscuro = new Color(21, 25, 28);
        Color Color_btn_noche_oscuro = new Color(64, 64, 64);
       
        
        
        Color ColorJPanel[] = {Menu_Izquierdo_Oscuro,Menu_Central_Oscuro,Menu_De_Fondo_Oscuro,ColorOscuro_txt_Modo_Oscuro,ColorOscuro_txt_Modo_Oscuro,ColorOscuro_txt_Modo_Oscuro,Color_btn_noche_oscuro};
        JPanel panelesColor[] ={ Menu_Lateral_Izquierdo,Menu_Central,jPanel2,Menu_deslizable_Panel_Contenedor_Botones,jPanel3,Contenedor_Licencia};
        general.CambiarColoresClaro(panelesColor, ColorJPanel, null, null, null, null, null);
    }//GEN-LAST:event_BTN_MODO_NOCHEMouseClicked

    private void BTN_MODO_DIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MODO_DIAMouseClicked
        //MODO CLARO 
        jButton1.setBackground(null);
        jButton2.setBackground(null);
        jButton3.setBackground(null);
        jButton4.setBackground(null);
        jButton5.setBackground(null);
        jButton6.setBackground(null);
        jButton7.setBackground(null);
        txt_CONFIGURACION.setBackground(null);
        txt_CHATBOT.setBackground(null);
        txt_BUSQUEDA.setBackground(null);

        //PARA PASAR A MODO CLARO
        Menu_deslizable_Panel_Contenedor_Botones.setBackground(Color.DARK_GRAY);
        BTN_MODO_NOCHE.setEnabled(true);
        TXT_NOCHE.setEnabled(true);
        BTN_MODO_NOCHE.setVisible(true);
        TXT_NOCHE.setVisible(true);
        Menu_Lateral_Izquierdo.setBackground(Color.DARK_GRAY);
        Menu_Central.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.GRAY);
        jPanel3.setBackground(Color.DARK_GRAY);

        Contenedor_Licencia.setBackground(Color.DARK_GRAY);
        TXT_NOCHE.setBackground(Color.DARK_GRAY);
        TXT_DIA.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_BTN_MODO_DIAMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        setState(ICONIFIED);//MINIMIZA LA VENTANA PRINCIPAL
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();// CIERRA LA VENTANA
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        setExtendedState(MAXIMIZED_BOTH);// MAXIMIZA LA VENTANA PRINCIPAL
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Dimension d = new Dimension(1350, 675);//REDIMENSIONA LA VENTANA
        this.setSize(d);//PARTE DE LA ACCIÓN DE REDIMENSIONAR
        this.setLocationRelativeTo(null);//CENTRA LA VENTANA
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        //ABRIR LA VENTANA DE INFORMES
       
    }//GEN-LAST:event_jButton7MouseClicked

    private void txt_CHATBOTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CHATBOTMouseEntered
        Color COLOR_AZUL_OSCURO = new Color(0, 0, 102);
        txt_CHATBOT.setBackground(COLOR_AZUL_OSCURO);
    }//GEN-LAST:event_txt_CHATBOTMouseEntered

    private void BTN_MODO_NOCHEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MODO_NOCHEMouseEntered
        Color COLOR_AZUL_OSCURO = new Color(54, 81, 207);
        BTN_MODO_NOCHE.setBackground(COLOR_AZUL_OSCURO);
    }//GEN-LAST:event_BTN_MODO_NOCHEMouseEntered

    private void BTN_MODO_NOCHEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MODO_NOCHEMouseExited
        BTN_MODO_NOCHE.setBackground(null);
    }//GEN-LAST:event_BTN_MODO_NOCHEMouseExited

    private void BTN_MODO_DIAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MODO_DIAMouseEntered
        Color COLOR_AZUL_OSCURO = new Color(54, 81, 207);
        BTN_MODO_DIA.setBackground(COLOR_AZUL_OSCURO);
    }//GEN-LAST:event_BTN_MODO_DIAMouseEntered

    private void BTN_MODO_DIAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MODO_DIAMouseExited
        BTN_MODO_DIA.setBackground(null);
    }//GEN-LAST:event_BTN_MODO_DIAMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    general.OpenWindows(WinUser_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton7AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7AncestorAdded

    private void txt_CONFIGURACIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CONFIGURACIONMouseClicked
general.OpenWindows(WinConf_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CONFIGURACIONMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
general.OpenWindows(WinCrearBG_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
general.OpenWindows(WindFnidad_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
general.OpenWindows(CrearProducto, null);  
CrearProducto.InicioProducto();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startt().setVisible(true);
            }
        });
    }
      public GENERAL_CLASS general = new GENERAL_CLASS();
        public  FAMILIA1 WinFm1_1;
        public  FAMILIA2 WinFm2_1  ;
        public  FAMILIA3 WinFm3_1  ;
        public  UNDMEDIDA WindFnidad_1 ;
        public  CrearBodegas WinCrearBG_1  ;
        public  Usuario WinUser_1 ;
        public  Configuracion WinConf_1;
        public  CrearProducto CrearProducto;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BTN_MENU;
    private javax.swing.JLabel BTN_MODO_DIA;
    private javax.swing.JLabel BTN_MODO_NOCHE;
    private javax.swing.JPanel Contenedor_Licencia;
    private javax.swing.JPanel Menu_Central;
    private javax.swing.JPanel Menu_Lateral_Izquierdo;
    private javax.swing.JPanel Menu_deslizable_Panel_Contenedor_Botones;
    private javax.swing.JLabel TXT_DIA;
    private javax.swing.JLabel TXT_NOCHE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel txt_Ag_Usuario;
    private javax.swing.JLabel txt_BUSQUEDA;
    private javax.swing.JLabel txt_CHATBOT;
    private javax.swing.JLabel txt_CONFIGURACION;
    private javax.swing.JLabel txt_Estadisticos;
    private javax.swing.JLabel txt_Informes;
    private javax.swing.JLabel txt_Licencia;
    private javax.swing.JLabel txt_Producto;
    private javax.swing.JLabel txt_Ventas;
    private javax.swing.JLabel txt_bodega;
    // End of variables declaration//GEN-END:variables
}
