/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOME;

import ALMACEN.CREARITEM.CrearBodegas;
import ALMACEN.CREARITEM.FAMILIA1;
import ALMACEN.CREARITEM.FAMILIA2;
import ALMACEN.CREARITEM.FAMILIA3;
import ALMACEN.CREARITEM.UNDMEDIDA;
import ALMACEN.Usuario;
import CLASS.GENERAL_CLASS;


/**
 *
 * @author Edwin
 */
public class Start extends javax.swing.JFrame  {

    /**
     * Creates new form start
     */
    public Start(FAMILIA1 WinFm1,FAMILIA2 WinFm2,FAMILIA3 WinFm3,UNDMEDIDA WindFnidad,CrearBodegas WinCrearBG,Usuario WinUser,Configuracion WinConf) {
        initComponents();
            WinFm1_1 =WinFm1;
            WinFm2_1= WinFm2 ;
            WinFm3_1  =WinFm3;
            WindFnidad_1 =WindFnidad ;
            WinCrearBG_1  =WinCrearBG;
            WinUser_1 =WinUser ;
            WinConf_1=WinConf;
    }

    private Start() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lupa_Buscar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Texto_Recargar = new javax.swing.JLabel();
        Texto_Agregar_Ciclos = new javax.swing.JLabel();
        Texto_estadístico = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Color_fondo = new javax.swing.JPanel();
        Titulo_Jetxcel = new javax.swing.JLabel();
        Fondo_Pantalla = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Image_Barra_Buscador = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        Texto_Escribe_para_buscar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Texto_Icono_Menu = new javax.swing.JLabel();
        Fondo_Menu_Izquierdo = new javax.swing.JLabel();
        Fondo_Central = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lupa_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar2.png"))); // NOI18N
        Lupa_Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lupa_Buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Lupa_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 19, 30, -1));

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_Recargar.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Texto_Recargar.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Recargar.setText("Recargar");
        jPanel1.add(Texto_Recargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        Texto_Agregar_Ciclos.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Texto_Agregar_Ciclos.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Agregar_Ciclos.setText("Agregar Ciclos");
        jPanel1.add(Texto_Agregar_Ciclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        Texto_estadístico.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Texto_estadístico.setForeground(new java.awt.Color(255, 255, 255));
        Texto_estadístico.setText("Estadísticos");
        jPanel1.add(Texto_estadístico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jButton7.setBackground(new java.awt.Color(102, 0, 204));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar2.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, -1));

        jButton8.setBackground(new java.awt.Color(102, 0, 204));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar_Ciclos.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, -1));

        jButton9.setBackground(new java.awt.Color(102, 0, 204));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Estadísticos.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Base_Datos.png"))); // NOI18N
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 70, 60));

        jButton11.setBackground(new java.awt.Color(51, 0, 153));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Configurar.png"))); // NOI18N
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 70, 60));

        jButton12.setBackground(new java.awt.Color(102, 0, 204));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("OBTENER LICENCIA");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 170, -1));

        Color_fondo.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout Color_fondoLayout = new javax.swing.GroupLayout(Color_fondo);
        Color_fondo.setLayout(Color_fondoLayout);
        Color_fondoLayout.setHorizontalGroup(
            Color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        Color_fondoLayout.setVerticalGroup(
            Color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(Color_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 550));

        Titulo_Jetxcel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        Titulo_Jetxcel.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_Jetxcel.setText("//Jetxcel");
        jPanel1.add(Titulo_Jetxcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Fondo_Pantalla.setBackground(new java.awt.Color(204, 0, 0));
        Fondo_Pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.jpg"))); // NOI18N
        jPanel1.add(Fondo_Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setOpaque(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 18, 340, 25));

        Image_Barra_Buscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Barra_Busqueda.png"))); // NOI18N
        getContentPane().add(Image_Barra_Buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 390, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ver_Ciclos.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 140, 180));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enviar_Ubicacion.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 100, 140, 180));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar_Funcionario.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 140, 180));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar_Usuario.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 140, 180));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ver_Medidores.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 140, 180));

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Chat_Bot.png"))); // NOI18N
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 140, 180));

        Texto_Escribe_para_buscar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Texto_Escribe_para_buscar.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Escribe_para_buscar.setText("Escribe para buscar");
        getContentPane().add(Texto_Escribe_para_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 16, 150, 30));

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_Icono_Menu.setBackground(new java.awt.Color(255, 255, 255));
        Texto_Icono_Menu.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        Texto_Icono_Menu.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Icono_Menu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Texto_Icono_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        Texto_Icono_Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Texto_Icono_Menu.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel2.add(Texto_Icono_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        Fondo_Menu_Izquierdo.setBackground(new java.awt.Color(204, 0, 0));
        Fondo_Menu_Izquierdo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.jpg"))); // NOI18N
        jPanel2.add(Fondo_Menu_Izquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 650, 550));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 60, 550));

        Fondo_Central.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo4.jpg"))); // NOI18N
        getContentPane().add(Fondo_Central, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 640, 550));

        setSize(new java.awt.Dimension(916, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
general.OpenWindows(WinFm1_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
general.OpenWindows(WinUser_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
general.OpenWindows(WinConf_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
general.OpenWindows(WinFm3_1, null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }
    public GENERAL_CLASS general = new GENERAL_CLASS();
    public  FAMILIA1 WinFm1_1;
    public  FAMILIA2 WinFm2_1  ;
    public  FAMILIA3 WinFm3_1  ;
    public  UNDMEDIDA WindFnidad_1 ;
    public  CrearBodegas WinCrearBG_1  ;
    public  Usuario WinUser_1 ;
    public  Configuracion WinConf_1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Color_fondo;
    private javax.swing.JLabel Fondo_Central;
    private javax.swing.JLabel Fondo_Menu_Izquierdo;
    private javax.swing.JLabel Fondo_Pantalla;
    private javax.swing.JLabel Image_Barra_Buscador;
    private javax.swing.JLabel Lupa_Buscar;
    private javax.swing.JLabel Texto_Agregar_Ciclos;
    private javax.swing.JLabel Texto_Escribe_para_buscar;
    private javax.swing.JLabel Texto_Icono_Menu;
    private javax.swing.JLabel Texto_Recargar;
    private javax.swing.JLabel Texto_estadístico;
    private javax.swing.JLabel Titulo_Jetxcel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
